{% set version = "3.9.0" %}

package:
  name: flit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: d75edf5eb324da20d53570a6a6f87f51e606eee8384925cd66a90611140844c7
  folder: source

build:
  script: cd source/ && FLIT_ROOT_INSTALL=1 python -m flit install --deps=none
  noarch: python
  entry_points:
    - flit = flit:main
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
    - docutils
    - requests
    - tomli-w
    - flit-core =={{ version }}
  run:
    - python >=3.6
    - pip
    - docutils
    - requests
    - tomli-w
    - flit-core =={{ version }}

test:
  imports:
    - flit
  commands:
    - flit --version

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
    - ocefpaf
