{% set version = "2.1.0" %}

package:
  name: flit-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: 6c954c3ec4e87a84fac55cca1a1d692a39354affa7c791eb49f6631b71ddbb40

build:
  number: 0
  skip: True  # [py2k]
  entry_points:
    - flit = flit:main

requirements:
  host:
    - python
    - pip
    - docutils
    - requests
    - pytoml
    - zipfile36  # [py<36]
  run:
    - python
    - docutils
    - requests
    - requests_download
    - zipfile36  # [py<36]
    - pytoml
    - pip

outputs:
  - name: flit-core
    script: install-core.sh  # [not win]
    script: install-core.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - pytoml
      run:
        - python
        - pytoml
      test:
        imports:
          - flit_core

  - name: flit
    script: install-flit.sh  # [not win]
    script: install-flit.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - docutils
        - requests
        - pytoml
        - zipfile36  # [py<36]
      run:
        - python
        - docutils
        - requests
        - requests_download
        - zipfile36  # [py<36]
        - pytoml
        - pip
        - {{ pin_subpackage('flit-core', exact=True) }}

    test:
      imports:
        - flit
      commands:
        - flit --version

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
    - ocefpaf
